services:
  web:
    image: vidhia/phpcrud:latest
    container_name: php-app
    ports:
      - "4000:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: prabhat@10
      MYSQL_DATABASE: prabhat
      MYSQL_USER: prabhat
      MYSQL_PASSWORD: prabhat@10
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: prabhat@10
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
